### PR TITLE
Benchmark

### LINKED ISSUE #1: benchmark build time
- [ ] determine method to benchmark jekyll build time (script?)
- [ ] benchmark impact on build time for various project sizes

### PR DESCRIPTION
**Pull request by maehr**
# Pull request

## Proposed changes

Adding a basic benchmark according to https://github.com/CollectionBuilder/cb-translate/issues/1

## Types of changes

- [x] New feature (non-breaking change which adds functionality).
- [ ] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by evanwill — APPROVED** [review]
Looks good to me! Tested on linux.

**Comment by maehr** [comment]
@evanwill thanks for reviewing the PR. Please tell me if I should open the same PR on https://github.com/CollectionBuilder/collectionbuilder-csv/ as well.
Best
Moritz

**Comment by evanwill** [comment]
@maehr not sure about the PR on collectionbuilder-csv --> we are already getting into complicated history confusion (of course 😉 )! We can pull in new features from cb-translate in bulk later, or you can do it for selected features now if you want. Up to you!

**Comment by maehr** [comment]
This is definitely up to you. Pull it when/if you need it.
Best
Moritz

**Pull request merged**
